language: node_js
cache: npm
node_js:
- '8'
- '10'
- '12'
install:
- npm install && cd sandbox && npm install && cd -
script:
- npm test
deploy:
  on:
    tags: true
    repo: Jesse-Cameron/graphql-access-checker
  provider: npm
  email: jessec.cameron@gmail.com
  api_key:
    secure: A3+4un+yapYtjKNGM5vbm5c1vyt6mdE0YAGKmm4HO50XZmHZHyymu+hBXPxoDFdTdH8BRbh/ESYeXO1akh8IAX/dp+/PSa6t2lpeOfV7EGWvvfr2rnDAwDy0TsuNCxKHvr5R19B1EKWLgnVuFr/eWgU0qHRNoiZn9aKTyQVQQy/ViQJLiDdPTWdHs4fPpXHeTseATKljBzd5f03ju+FB/iXek3jkfUpjAMDt/1UuzSFbKoWuor9aW72ImriUa1A0oMYYnNaGVihQVrMcZpiS/0tLRK8AJrdqqXgXnfy0fDJdy5ypDG79DuiVsA0w57AttO9K7r+SN3DU+AxEPkeMzkSYYPvKMrPNIXvQLMhLXqOGxZ5uATQ1+FtSZ0f/HZZPAN3Tjlsu38Lxll5beVuvywzhxV6f6FcmwlVVbZje1TTpt7hmyVCTxVbmJNV71nzqTRE+m7vtSsF10sToClGTr58mgNvbzXzYR1EWCnS/lLeSj0pvtBW4eF4ecwHJ7Yz+M/+ll0m0XbTFhtyv2y3qAclWPzUAc10eMD/KIh3ICRSzbThls3OM4cIPOHI7XJcJAx6ITqGIN1JAPtHZlXLijGSKjtGC9NPB63QqDbd2e3N8mmHJUusUsc+3EBKfynXIMYeM1I0pAXoT9CRmfhFP7PmhXBVqbBse6+48GFkGW8Y=
